name: Vercel Preview Deployment

env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
   API_KEY: ${{ secrets.API_KEY }}   
   BASE_URL: ${{ vars.BASE_URL }}

on:
   push:
      branches-ignore: [main]
      paths:
         - "weather-app/**"
   pull_request:
      branches-ignore: [main]
      paths:
         - "weather-app/**"

jobs:
   Deploy:
      runs-on: ubuntu-latest
      container:
         image: node:20

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 20

         - name: Install weather-app dependencies
           run: |
              cd weather-app
              echo ${{ secrets.API_KEY }}
              echo ${{ vars.BASE_URL }}
              npm ci

         - name: Run ESLint (weather-app)
           run: |
              cd weather-app
              npm run lint

         - name: Run tests (weather-app)
           run: |
              cd weather-app
              npm test

         - name: Install Vercel CLI
           run: npm install --global vercel

         - name: Pull Vercel Environment Information
           run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

         - name: Build Project Artifacts
           run: |
              export BASE_URL="${{ vars.BASE_URL }}"
              export API_KEY="${{ secrets.API_KEY }}"
              vercel build --token=${{ secrets.VERCEL_TOKEN }}

         - name: Deploy Project Artifacts
           run: |
              export BASE_URL="${{ vars.BASE_URL }}"
              export API_KEY="${{ secrets.API_KEY }}"
              vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
